name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Make release
        run: |
          dotnet restore
          dotnet publish src/Howestprime.Backoffice/ --os linux /t:PublishContainer /p:PublishProfile=test /p:ContainerImageName=howestprime-backoffice

      - name: Zip the release
        run: |
          cd build && zip -r ../build.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: Log in to Azure
        run: |
          az login --service-principal \
          -u ${{ secrets.HOWESTPRIME_WIDE_CI_SERVICE_PRINCIPAL }} \
          -p ${{ secrets.HOWESTPRIME_WIDE_CI_SERVICE_PRINCIPAL_PASSWORD }} \
          --tenant ${{ vars.AZ_TENANT_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZ_BACKOFFICE_WEBAPP }}
          package: build.zip
